---
name: Upload Image

on: #  yamllint disable-line rule:truthy
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"
          architecture: x64

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "${findandreplace.version}"
          replace: ${{ github.ref }}
          include: "src/main/resources/plugin.yml"
          regex: false

      - name: Run the Maven verify phase
        run: mvn verify -Drevision=${{ github.ref }} -f "pom.xml"

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/NoSnow*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
